myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('', include('pages.urls')),

    path('cart', include('cart.urls', namespace='cart')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),


]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),

    path('product_detail/<int:id>/', views.product_detail, name='product_detail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Količina')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

myshop/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Tvoja korpa
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        Moja narudžba:
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, KM {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Tvoja korpa je prazna.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Slika</th>
                        <th>Proizvod</th>
                        <th>Kličina</th>
                        <th>Ukloni</th>
                        <th>Cijena jednog</th>
                        <th>Cijena</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Izmjeni" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Ukloni</a>
                            </td>
                            <td>KM {{ item.price }}</td>
                            <td>KM {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Ukupno</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>KM {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "shop:product_list" %}" class="btn btn-default">Nastavi kupovinu</a>
            <a href="{% url "orders:order_create" %}" class="btn btn-primary">Provjeri</a>
        </p>
        </div>
    </div>
{% endblock %}