myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('', include('pages.urls')),

    path('cart', include('cart.urls', namespace='cart')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),

    path('product_detail/<int:id>/', views.product_detail, name='product_detail'),
]

myshop/shop/models.py
from django.db import models
from django.urls import reverse

class Product(models.Model):

    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id])

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from cart.forms import CartAddProductForm


def product_list(request):

    products = Product.objects.filter(available=True)


    context = {

        'products': products
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id):
    product = get_object_or_404(Product, id=id, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

myshop/shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Druga Pomoc</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">



        <!--For Plugins external css-->
        <link rel="stylesheet" href="{% static 'css/animate/animate.css' %}" />
        <link rel="stylesheet" href="{% static 'css/plugins.css' %}" />

        <!--Theme custom css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <!--Theme Responsive css-->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
</head>
<body>
{% include 'shop/navbar.html' %}

<div class="container">
    <div class="row" style="margin-top: 6%">
         <button class="btn btn-info pull-right">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    Moja narudžba:
                    <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                        {{ totail_items }} piva {{ totail_items|pluralize }}, KM: {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Tvoja korpa je prazna.
                {% endif %}
            {% endwith %}
         </button>
    </div>
</div>
{% block content %}


{% endblock %}

{% include 'shop/footer.html' %}

        <script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/jquery-easing/jquery.easing.1.3.js' %}"></script>
        <script src="a{% static 'js/wow/wow.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

myshop/shop/templates/shop/footer.html
{% load static %}

        <section id="footer_widget" class="footer_widget">
            <div class="container">
                <div class="row">
                    <div class="footer_widget_content text-center">
                        <div class="col-md-4">
                            <div class="single_widget wow fadeIn" data-wow-duration="2s">
                                <h3>Evo gdje se nalazimo</h3>

                                <div class="single_widget_info">
                                        {% for content in contents %}
                                        {{ content.address|safe }}
                                        {% endfor %}
                                        <p><span class="phone_email">Telefon:

                                    {% for content in contents %}
                                    {{ content.phone }}

                                        </span>
                                        <span>Email: {{ content.email }}</span></p>
                                    {% endfor %}
                                </div>

                                <div class="footer_socail_icon">
                                    <a href=""><i class="fa fa-facebook"></i></a>
                                    <a href=""><i class="fa fa-google-plus"></i></a>
                                    <a href=""><i class="fa fa-twitter"></i></a>
                                    <a href=""><i class="fa fa-linkedin"></i></a>
                                    <a href=""><i class="fa fa-pinterest-p"></i></a>
                                    <a href=""><i class="fa fa-youtube"></i></a>
                                    <a href=""><i class="fa fa-phone"></i></a>
                                    <a href=""><i class="fa fa-camera"></i></a>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="single_widget wow fadeIn" data-wow-duration="4s">
                                <h3>Za Vas smo uvijek dostupni</h3>

                                <div class="single_widget_info">
                                    <span class="date_day">

                                        {% for content in contents %}
                                        {{ content.working_time|safe }}
                                        {% endfor %}
                                        </span>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="single_widget wow fadeIn" data-wow-duration="5s">
                                <h3>Kontaktirajte nas</h3>

                                <div class="single_widget_form text-left">
                                    <form action="{% url 'contact' %}" method="POST" id="formid">
                                        {% csrf_token %}
                                        <div class="form-group">

                                            <input type="text" class="form-control" name="name" placeholder="Ime" required="">
                                        </div>

                                        <div class="form-group">

                                            <input type="email" class="form-control" name="email" placeholder="Email" required="">
                                        </div>

                                        <div class="form-group">

                                            <input type="text" name="title" class="form-control" placeholder="Naslov">
                                        </div> <!-- end of form-group -->

                                        <div class="form-group">

                                            <textarea class="form-control" name="message" rows="3" placeholder="Poruka"></textarea>
                                        </div>

                                        <input type="submit" value="Pošalji poruku" class="btn btn-primary">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!--Footer-->
        <footer id="footer" class="footer">
            <div class="container text-center">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="copyright wow zoomIn" data-wow-duration="3s">
							<p>Made with <i class="fa fa-heart"></i> for Biki by Petar Janjić</a>2019. All Rights Reserved</p>
						</div>
                    </div>
                </div>
            </div>
        </footer>

myshop/shop/templates/shop/navbar.html
{% load static %}

		<div class='preloader'><div class='loaded'>&nbsp;</div></div>
        <header id="home" >
            <div class="header_top_menu clearfix">
                <div class="container">
                    <div class="row">
                        <div class="col-md-5 col-md-offset-3 col-sm-12 text-right">
                            <div class="call_us_text">
								<a href="{% url 'shop:product_list' %}"><i class="fa fa-clock-o"></i> Naruci pivo 24/7</a>
								<a href=""><i class="fa fa-phone"></i>
                                    {% for content in contents %}
                                    {{ content.phone }}
                                    {% endfor %}</a>
							</div>
                        </div>

                        <div class="col-md-4 col-sm-12">
                            <div class="head_top_social text-right">
                                <a href=""><i class="fa fa-facebook"></i></a>
                                <a href=""><i class="fa fa-google-plus"></i></a>
                                <a href=""><i class="fa fa-twitter"></i></a>
                                <a href=""><i class="fa fa-linkedin"></i></a>
                                <a href=""><i class="fa fa-youtube"></i></a>
                                <a href=""><i class="fa fa-phone"></i></a>
                                <a href=""><i class="fa fa-camera"></i></a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <!-- End navbar-collapse-->


            <div class="main_menu_bg">
                <div class="container">
                    <div class="row">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    <a class="navbar-brand our_logo" href="{%url 'index' %}"><img src="{% static 'images/logo.png' %}" alt="" /></a>
                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                                    <ul class="nav navbar-nav navbar-right">
                                        <li><a href="{%url 'index' %}">Početna</a></li>
                                        <li><a href="{%url 'index' %}#abouts">O Nama</a></li>
                                        <li><a href="{%url 'index' %}#features">O Pivu</a></li>
                                        <li><a href="{% url 'shop:product_list' %}">Kupi</a></li>
                                        <li><a href="{%url 'index' %}#mobaileapps">Aplikacija</a></li>
                                        <li><a href="{%url 'index' %}#footer_widget">Kontakt</a></li>

                                    </ul>
                                </div><!-- /.navbar-collapse -->
                            </div><!-- /.container-fluid -->
                        </nav>
                    </div>
                </div>
            </div>
            </header> <!-- End Header Section -->